name: Build and Publish Docker Images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build bonus microservice with Maven
      run: cd microservice-istio-bonus && mvn -B package --file pom.xml
    - name: Create Docker images for bonus microservice
      run: cd microservice-istio-bonus && sh ./docker-build.sh
    - name: Log into registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Push image for bonus microservices
      run: |
        IMAGE_PREFIX=${{ secrets.DOCKER_USERNAME }}
        docker tag microservice-istio-bonus:1 $IMAGE_PREFIX/microservice-istio-bonus:1
        docker push $IMAGE_PREFIX/microservice-istio-bonus:1


    - name: Build other microservices with Maven
      run: cd microservice-istio-demo && mvn -B package --file pom.xml
    - name: Create Docker images for other microservicee
      run: cd microservice-istio-demo && sh ./docker-build.sh
    - name: Log into registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Push image for other microservices
      run: |
        IMAGE_PREFIX=${{ secrets.DOCKER_USERNAME }}
        docker tag microservice-istio-apache $IMAGE_PREFIX/microservice-istio-apache:latest
        docker push $IMAGE_PREFIX/microservice-istio-apache:latest
        docker tag microservice-istio-postgres $IMAGE_PREFIX/microservice-istio-postgres:latest
        docker push $IMAGE_PREFIX/microservice-istio-postgres:latest
        docker tag microservice-istio-shipping:1 $IMAGE_PREFIX/microservice-istio-shipping:1
        docker push $IMAGE_PREFIX/microservice-istio-shipping:1
        docker tag microservice-istio-invoicing:1 $IMAGE_PREFIX/microservice-istio-invoicing:1
        docker push $IMAGE_PREFIX/microservice-istio-invoicing:1
        docker tag microservice-istio-order:1 $IMAGE_PREFIX/microservice-istio-order:1
        docker push $IMAGE_PREFIX/microservice-istio-order:1
